---
title: "COMPSCIX 415.2 Homework 1"
author: "Xinmiao Tan"
date: "June 6, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My Github repository for my assignments can be found at this URL: [https://github.com/xinmiaotan/compscix-415-2-assignments](https://github.com/xinmiaotan/compscix-415-2-assignments)


```{r cars r load_packages, warning=FALSE, message=FALSE}
library(mdsr) 
library(tidyverse)
data("WorldCities")
```

A data frame with 23,018 observations on the following 10 variables.
Some variable names: code, name, latitude, longitude, country, countryRegion, population, regionCode, region, date

```{r}
glimpse(WorldCities)
WorldCities <- head(WorldCities, 200) # 200 rows
country_col <- WorldCities$country
unique(country_col)
region_col <- WorldCities$region
unique(region_col)

WorldCities %>% select(country) %>% unique()

WorldCities %>% ggplot(aes(x = population)) + 
    geom_histogram()+
    xlab('City Population')+
    ylab('City Count') +
    ggtitle('City Histogram') +
    theme_bw()
 
```

